### ISSUE TITLE
[BUG] [ws-scan.py] Nexus integration tool have issue on uploading data

### ISSUE THREAD

**Issue by edwardhu** [whitesource-ps/whitesource-nexus-integration#7]
**Bug Description**  

**Steps to Reproduce**  
1. Set up params.config file
2. Execute the ws-scan.py file and waiting for processing.
3. Get the log file, we can see the details.

**Environment Details**  
 - OS: macOS 11.3
 - Unified Agent Version Newest

**Context**  
We did download the Nexus integration tool to scan the nexus library with the Maven package manager.
But got the result with upload scanning results failed.
It seems the integration tool still did not offer configure parameters to set the WhiteSource user key.
[wss-scan.log](https://github.com/whitesource-ps/whitesource-nexus-integration/files/6418796/wss-scan.log)
[whitesource.0.log](https://github.com/whitesource-ps/whitesource-nexus-integration/files/6418797/whitesource.0.log)

**Comment by NatalyaDalid** [comment]
Hey Edward.
There is an option to scan without a user key is required. But you are definitely right for cases when this option is disabled. 
We have added a user key as an input parameter. 
Thank you for this catch. 
A new version has been released.
